[package]
name = "rsoxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
serialport = "4.2.0"
tokio = { version = "1.26.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
